### ISSUE TITLE
Example doesn't work in Firefox

### ISSUE THREAD

**Issue by ockle** [ezekg/flint#44]
I've just come across Flint, and was checking out the docs. However, the example doesn't look correct in Firefox:

![flint - a flexible sass-based grid system built for rapid responsive development](https://cloud.githubusercontent.com/assets/2755069/12868727/5f63456c-cd04-11e5-82b0-48fd8472efd2.png)

**Comment by ezekg** [comment]
I can't see the image, but after looking in Firefox, this actually looks like a difference because of how Firefox is rendering the `outline` property. If you change the `outline` to `border`, it looks _more correct_. It's a little off due to pixel rounding, but nothing that is noticeable or which breaks the layout.

Here's a screenshot, (you can simply copy+paste an image into the GitHub editor and it'll automatically embed it, so you don't need to host it on imgur, btw)

![image](https://cloud.githubusercontent.com/assets/6979737/12868325/911c30ae-ccc9-11e5-9e0f-5c276474846c.png)

**Comment by ockle** [comment]
@ezekg Apologies about the image going missing, I've rectified that in the original report. Hopefully you can rectify the example, as to be honest I was presuming the error was in Flint, and was put off using it :( I presume I won't be the only one who thought the same.

**Comment by ezekg** [comment]
Honestly, [this is something that you're likely going to hit with almost every grid system](https://www.palantir.net/blog/responsive-design-s-dirty-little-secret). It looks like Chrome and Safari round pixels up, while Firefox rounds down, thus adding space like you see. In any _real_ layout, this is completely unnoticeable. I wouldn't look to far into it.

**Comment by ockle** [comment]
@ezekg I was meaning changing the example outline to border so it at least looks like your screenshot and not mine, and doesn't look like an off-putting issue with the grid system.

**Comment by ezekg** [comment]
Gotcha. That example will be going away once I get some time to finish up a redesign of the site, which will include a lot more examples and production sites made with Flint. Thanks for the issue though. I hope you give Flint another chance even if it gave you a bad first impression with that example in Firefox. :+1:
